import Footer from "./components/footer/Footer";
import Nav from "./components/nav/Nav";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Minimal Apple Clone -- Dawood",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav state={true} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
